# Generated by Django 5.0.4 on 2024-05-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='fallback.png', upload_to='images/profiles/'),
        ),
    ]
