# Generated by Django 5.0.4 on 2024-05-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('s_manager', 'Sales Manager'), ('receptionist', 'Receptionist'), ('manager', 'Manager'), ('client', 'Client')], max_length=20),
        ),
    ]
