# Generated by Django 5.0.3 on 2024-04-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offlinesaleslog',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='onlinesale',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='purchaselog',
            old_name='transcation_id',
            new_name='transcation',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
