# Generated by Django 5.0.3 on 2024-04-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_rename_transaction_id_offlinesaleslog_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_code',
            field=models.TextField(default='ABC', unique=True),
            preserve_default=False,
        ),
    ]
