# Generated by Django 5.0.3 on 2024-04-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_supplier_supplier_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_code',
            field=models.TextField(max_length=5, unique=True),
        ),
    ]
