# Generated by Django 5.0.3 on 2024-04-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_supplier_supplier_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_type',
        ),
        migrations.AddField(
            model_name='equipment',
            name='weight_class',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_info',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
