# Generated by Django 5.0.3 on 2024-04-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_equipment_equipment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
