# Generated by Django 5.0.3 on 2024-04-18 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_supplier_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.supplier')),
            ],
        ),
    ]
