# Generated by Django 5.0.3 on 2024-04-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_orderhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='amount',
            new_name='count',
        ),
    ]
