# Generated by Django 5.0.3 on 2024-04-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_rename_amount_orderhistory_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='item_name',
            field=models.CharField(default='Unknown', max_length=30),
            preserve_default=False,
        ),
    ]
