# Generated by Django 5.0.4 on 2024-05-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_orderhistory_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='supplier',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='supplier_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
