# Generated by Django 5.0.4 on 2024-05-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_remove_orderhistory_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='fallback.png', upload_to='equipments/'),
        ),
    ]
