# Generated by Django 5.0.4 on 2024-05-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_equipment_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='images/equipments/fallback.png', upload_to='images/equipments/'),
        ),
    ]
