# Generated by Django 5.0.4 on 2024-05-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_alter_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.FileField(default='media/images/equipments/fallback.png', upload_to='media/images/equipments/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='manufracturer',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
