# Generated by Django 5.0.4 on 2024-05-20 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_remove_sale_equipment_remove_sale_sales_made_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_per', models.FloatField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.equipment')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='equipment.transactionlog')),
            ],
        ),
    ]
