# Generated by Django 5.0.4 on 2024-05-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_sales_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='item_manufracturer',
            field=models.CharField(default='New Age', max_length=50),
            preserve_default=False,
        ),
    ]
