# Generated by Django 5.0.4 on 2024-05-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0024_alter_orderhistory_item_manufracturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(default='Not Delivered', max_length=20),
        ),
    ]
